Avoid attempting to re-read inventory file from unmounted partition
e9d686ae17bfcad5383f2d89d6bf848c3abd9a3b triggers an unmount of backup_fs
before we're done with it, causing a restoration failure in 10.10.25:

 INFO     [2025-03-19 14:33:50] INSTALL FAILED.
 INFO     [2025-03-19 14:33:50] A fatal exception occurred:
 INFO     [2025-03-19 14:33:50] Traceback (most recent call last):
   File "/opt/xensource/installer/install.py", line 274, in go
     restore.restoreFromBackup(backup, progress)
   File "/opt/xensource/installer/restore.py", line 214, in restoreFromBackup
     branding = util.readKeyValueFile(os.path.join(backup_fs.mount_point, constants.INVENTORY_FILE))
   File "/opt/xensource/installer/util.py", line 322, in readKeyValueFile
     f = open(filename, "r")
 IOError: [Errno 2] No such file or directory: '/tmp/restore-backup-hrJwAR/etc/xensource-inventory'


Fortunately that data we want was already loaded, so this is a minimal fix.

Signed-off-by: Yann Dirson <yann.dirson@vates.tech>